apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-jenkins 
  labels:
    app: teamcontainer
spec:
  selector:
    matchLabels:
        app: teamcontainer
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: teamcontainer
    spec:
      containers:
        - name: teamcontainer
          image: 674583976178.dkr.ecr.us-east-2.amazonaws.com/teamimagerepo:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
